services:
  mysqldb:
    image: "mysql:8.0.26"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: login_demo
    volumes:
      - mysqldb_data:/var/lib/mysql

  redis:
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - redis_data:/data

#  db-setup:
#    image: mysql:8.0.26
#    command: ["sh", "-c", "exec mysql -hmysqldb -uroot -p${MYSQL_ROOT_PASSWORD} login_demo < /db-setup/backup.sql"]
#    volumes:
#      - ./backup.sql:/db-setup/backup.sql
#    depends_on:
#      - mysqldb

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./target/demo-app.jar:/demo-app.jar
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/login_demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ''

volumes:
  mysqldb_data:
  redis_data:
